# Generated by Django 2.2.9 on 2020-01-23 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='montedb.Person')),
                ('iban', models.CharField(max_length=32)),
                ('partner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='montedb.Adult')),
            ],
            bases=('montedb.person',),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='montedb.Person')),
                ('birth_place', models.CharField(max_length=255)),
                ('care_time', models.IntegerField(default=4)),
                ('kita', models.BooleanField()),
            ],
            bases=('montedb.person',),
        ),
        migrations.CreateModel(
            name='AdultsChildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinship', models.CharField(choices=[('PR', 'Parent')], default='PR', max_length=2)),
                ('adult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montedb.Adult')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montedb.Child')),
            ],
        ),
    ]
