# Generated by Django 2.2.9 on 2020-01-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('salary', 'Salary'), ('income', 'Income'), ('unemployment', 'Unemployment'), ('maintenance', 'Maintenance'), ('deduction', 'Deduction')], default='salary', max_length=20)),
                ('adult', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='montedb.Adult')),
            ],
        ),
    ]
