# Generated by Django 2.0.13 on 2020-01-08 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='montedb.Person')),
                ('iban', models.CharField(max_length=32)),
                ('partner_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='montedb.Adult')),
            ],
            bases=('montedb.person',),
        ),
    ]
