# Generated by Django 2.0.13 on 2019-11-24 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0002_auto_20191124_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='care_time',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
    ]
