# Generated by Django 2.0.13 on 2020-01-08 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0002_created_adult_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='partner_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='montedb.Adult'),
        ),
    ]
