# Generated by Django 2.2.9 on 2020-01-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0002_added_phone_number_email_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adultchild',
            options={'verbose_name': 'Degree of kinship', 'verbose_name_plural': 'Degrees of kinship'},
        ),
        migrations.AddField(
            model_name='adult',
            name='children',
            field=models.ManyToManyField(through='montedb.AdultChild', to='montedb.Child'),
        ),
        migrations.AlterField(
            model_name='adultchild',
            name='kinship',
            field=models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('grandmother', 'Grandmother'), ('grandmother', 'Grandfather'), ('other', 'Other')], default='mother', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='adultchild',
            unique_together={('adult', 'child'), ('child', 'kinship')},
        ),
    ]
