# Generated by Django 2.2.9 on 2020-02-02 07:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0003_added_kinship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_to', models.DateField(default=datetime.date.today)),
                ('document', models.FileField(upload_to='documents/')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montedb.Child')),
            ],
        ),
    ]
