# Generated by Django 2.2.9 on 2020-02-05 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0003_added_kinship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='adult',
            options={'verbose_name': 'Adult', 'verbose_name_plural': 'Adults'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Child', 'verbose_name_plural': 'Children'},
        ),
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'verbose_name': 'E-Mail address', 'verbose_name_plural': 'E-Mail addresses'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Income', 'verbose_name_plural': 'Incomes'},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'Phone number', 'verbose_name_plural': 'Phone numbers'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='House number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=255, verbose_name='ZIP code'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adults', to='montedb.Address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='children',
            field=models.ManyToManyField(through='montedb.AdultChild', to='montedb.Child', verbose_name='Children'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='iban',
            field=models.CharField(max_length=32, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='montedb.Adult', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='adultchild',
            name='adult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montedb.Adult', verbose_name='Adult'),
        ),
        migrations.AlterField(
            model_name='adultchild',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montedb.Child', verbose_name='Child'),
        ),
        migrations.AlterField(
            model_name='adultchild',
            name='kinship',
            field=models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('grandmother', 'Grandmother'), ('grandmother', 'Grandfather'), ('other', 'Other')], default='mother', max_length=20, verbose_name='Degree of kinship'),
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_place',
            field=models.CharField(max_length=255, verbose_name='Birth place'),
        ),
        migrations.AlterField(
            model_name='child',
            name='care_time',
            field=models.IntegerField(default=4, verbose_name='Care time'),
        ),
        migrations.AlterField(
            model_name='child',
            name='kita',
            field=models.BooleanField(verbose_name='Day-care centre'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='adult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montedb.Adult', verbose_name='Adult'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='email_address',
            field=models.EmailField(max_length=254, verbose_name='E-Mail address'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('work', 'Work')], default='private', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='income',
            name='adult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montedb.Adult', verbose_name='Adult'),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('salary', 'Salary'), ('income', 'Income'), ('unemployment', 'Unemployment'), ('maintenance', 'Maintenance'), ('deduction', 'Deduction')], default='salary', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='adult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montedb.Adult', verbose_name='Adult'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='type',
            field=models.CharField(choices=[('privat', 'Private'), ('work', 'Work'), ('mobile', 'Mobile'), ('fax', 'Fax')], default='privat', max_length=10, verbose_name='Type'),
        ),
    ]
