# Generated by Django 2.0.13 on 2020-01-09 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0003_adult_self_reference_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adult',
            name='partner_to',
        ),
        migrations.AddField(
            model_name='adult',
            name='partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='montedb.Adult'),
        ),
    ]
