# Generated by Django 2.0.13 on 2020-01-18 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0004_adult_partner_one_to_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultsChildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinship', models.CharField(choices=[('PR', 'Parent')], default='PR', max_length=2)),
                ('adult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montedb.Adult')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montedb.Child')),
            ],
        ),
    ]
