# Generated by Django 2.2.9 on 2020-02-05 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0004_added_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='club_member',
            field=models.BooleanField(default=False, verbose_name='Club member'),
        ),
        migrations.AddField(
            model_name='adult',
            name='household_size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Household size'),
        ),
        migrations.AddField(
            model_name='adult',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
    ]
