# Generated by Django 2.2.9 on 2020-02-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0004_added_ruling'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruling',
            name='type',
            field=models.CharField(choices=[('SR', 'Some Ruling'), ('SOR', 'Some Other Ruling')], default='SR', max_length=10),
        ),
    ]
