# Generated by Django 2.2.9 on 2020-02-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0005_added_fields_to_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultchild',
            name='liable',
            field=models.BooleanField(default=False, verbose_name='Liable to contribution'),
        ),
        migrations.AddField(
            model_name='adultchild',
            name='payer',
            field=models.BooleanField(default=False, verbose_name='Payer'),
        ),
    ]
