# Generated by Django 2.2.9 on 2020-02-05 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0006_add_fields_to_adultchild'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ext_day_time', 'Extended day time'), ('ext_care_time', 'Extended care time'), ('right_to_request', 'Right to request and vote (available care service)'), ('fee_by_county', 'Fee payment by county'), ('lunch_by_county', 'Lunch payment by county')], max_length=10, verbose_name='Ruling type')),
                ('valid_from', models.DateField(default=datetime.date.today, verbose_name='Valid from')),
                ('valid_to', models.DateField(default=datetime.date.today, verbose_name='Valid to')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montedb.Child', verbose_name='Child')),
            ],
        ),
    ]
