# Generated by Django 2.2.9 on 2020-02-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0007_ruling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruling',
            options={'verbose_name': 'Ruling', 'verbose_name_plural': 'Rulings'},
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('work', 'Work'), ('mobile', 'Mobile'), ('fax', 'Fax')], default='private', max_length=10, verbose_name='Type'),
        ),
    ]
