# Generated by Django 2.2.9 on 2020-02-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0009_alter_field_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='iban',
            field=models.CharField(blank=True, max_length=32, verbose_name='IBAN'),
        ),
    ]
