# Generated by Django 2.2.9 on 2020-02-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0010_alter_field_iban_on_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultchild',
            name='max_contribution',
            field=models.BooleanField(default=False, verbose_name='Max contribution'),
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('salary', 'Salary'), ('income', 'Income'), ('unemployment', 'Unemployment'), ('other_payments', 'Other payments'), ('deduction', 'Deduction')], default='salary', max_length=20, verbose_name='Type'),
        ),
    ]
