# Generated by Django 2.2.10 on 2020-03-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0011_add_field_max_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentalContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(verbose_name='Income')),
                ('type', models.CharField(choices=[('school_fee', 'School fee'), ('after_school_fee', 'After school fee'), ('kindergarten_le_30h_fee', 'Kindergarten (up to 30 hours)'), ('kindergarten_gt_30h_fee', 'Kindergarten (more than 30 hours)'), ('nursery_le_30h_fee', 'Nursery (up to 30 hours)'), ('nursery_gt_30h_fee', 'Nursery (more than 30 hours)')], max_length=10, verbose_name='Contribution type')),
                ('children', models.SmallIntegerField(verbose_name='Number of children')),
                ('contribution', models.SmallIntegerField(verbose_name='Contribution')),
            ],
        ),
    ]
