# Generated by Django 2.2.10 on 2020-03-15 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0012_parentalcontribution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentalcontribution',
            options={'verbose_name': 'Parental Contribution', 'verbose_name_plural': 'Parental Contributions'},
        ),
        migrations.AlterUniqueTogether(
            name='parentalcontribution',
            unique_together={('type', 'income', 'children')},
        ),
    ]
