# Generated by Django 2.2.10 on 2020-04-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('montedb', '0014_parental_contribution_type_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='children',
            field=models.ManyToManyField(related_name='adults', through='montedb.AdultChild', to='montedb.Child', verbose_name='Children'),
        ),
        migrations.AlterField(
            model_name='income',
            name='adult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='montedb.Adult', verbose_name='Adult'),
        ),
    ]
